### Get all users
GET http://localhost:8080/users
Accept: application/json


### Add a new user (JSON)
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 3,
  "email": "charlie@i.ua"
}